### ISSUE TITLE
Path to black.toml not working as expected.

### ISSUE THREAD

**Issue by GuilhermeFreire** [HeavenVolkoff/foundation#2]
There's an issue with `format.sh`'s execution. When running the script from anywhere other than the project's root folder, an error occurs:
```bash
Usage: black [OPTIONS] [SRC]...

Error: Error reading configuration file: [Errno 2] No such file or directory: './black.toml'
```
The TOML file isn't found since the script seeks it using a relative path. This is likely due to the `black_file=./black.toml` property in `.editorconfig`.

In order to fix this, the script should probably account for the user's current working directory and modify this property ad hoc when running black.

**Comment by HeavenVolkoff** [comment]
Hey,
format.sh is now located in it's [own repository](https://github.com/HeavenVolkoff/format.sh).
Could you test the version available there? I think this bug is fixed. If not you can open a new issue there.
